# Architecture
arch: resnet 
structure: False
# ===== Dataset ===== #
data: datasets
set: CIFAR10


# ===== Learning Rate Policy ======== #
optimizer: sgd
lr: 0.1


# ===== Network training config ===== #
epochs: 100
weight_decay: 0.0005
momentum: 0.9
batch_size: 256
