# Architecture
arch: VGG_Bee 
structure: True
# ===== Dataset ===== #
data: datasets
set: svhn


# ===== Learning Rate Policy ======== #
lr: 0.1
lr_policy: cosine_lr

# ===== Network training config ===== #
epochs: 100
weight_decay: 0.0005
momentum: 0.9
batch_size: 256

